Repository az-digital/arizona-bootstrap, pull requests merged in 2020-11, with the labels that each got.

#189 Closes #188: Fixed CDN asset paths in _config_template.yml.
  _config_template.yml
Labels: bug

#181 Closes #180: Fix incorrect markup in image cap bottom card example.
  site/docs/2.0/components/card.md
Labels: bug, documentation, hacktoberfest-accepted

#190 Feature/182 add arizona header into arizona bootstrap
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.js.map
  scss/_custom-styles.scss
  site/_data/nav.yml
  site/docs/2.0/assets/css/docs.min.css
  site/docs/2.0/assets/css/docs.min.css.map
  site/docs/2.0/components/arizona-header.md
  site/docs/2.0/components/background-wrappers.md
Labels: enhancement

#167 Update light gray text-muted colors to pass WCAG 2.0 AAA accessibility standards.
  dist/css/arizona-bootstrap.css
  scss/_custom-variables.scss
  scss/_dropdown.scss
  site/docs/2.0/components/dropdowns.md
Labels: hacktoberfest-accepted
