Repository az-digital/arizona-bootstrap, pull requests merged in 2021-09, with the labels that each got.

#356 Closes #354 Update landing grid styles and documentation to match redesign
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_card.scss
  site/content/docs/2.0/components/card.md
Labels: documentation, enhancement

#361 Closes #208: Integrate the Arizona-specific icons into Arizona Bootstrap
  site/content/docs/2.0/extend/icons.md
  site/content/docs/2.0/getting-started/introduction.md
  site/layouts/partials/stylesheet.html
Labels: documentation, enhancement

#358 Closes #357: Update package.json dev dependencies.
  Dockerfile
  build/vnu-jar.js
  package-lock.json
  package.json
Labels: dependencies

#367 Closes #362: Add some documentation about which version of az-icons to use
  site/content/docs/2.0/icons.md
Labels: documentation
