Repository az-digital/arizona-bootstrap, pull requests merged in 2022-09, with the labels that each got.

#532 Closes #537: Restyle breadcrumbs
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/_breadcrumb.scss
  scss/_pagination.scss
  scss/arizona-bootstrap.scss
  site/content/docs/2.0/components/breadcrumb.md
  site/content/docs/2.0/components/collapse.md
  site/layouts/partials/alert-warning-material-design.md
  site/layouts/shortcodes/alert.html
Labels: documentation, enhancement

#560 Closes #549, Closes #513: Bump dependency versions (including jquery), and change Java support for linting.
  Dockerfile
  config_template.yml
  package-lock.json
  package.json
Labels: dependencies, high priority

#565 Closes #563: Copy the file ownership fix-up from the Action that builds review sites on PRs.
  .github/workflows/release.yml
  .github/workflows/review-site.yml
Labels: bug, high priority

#570 Closes #569: Use a temporary directory for the staged SHA value.
  .github/workflows/release.yml
Labels: bug

#571 Reverting incomplete 2.0.17 release.
  package.json
Labels: bug

#572 Closes #562: Update breadcrumb styles
  scss/_breadcrumb.scss
Labels: enhancement

#576 Closes #575: Increase the number of commits available to the Action that pushes modified CSS or JS files.
  .github/workflows/review-site.yml
Labels: bug

#568 Closes #567: Use bot user token instead of old SSH key to push changes back to repo.
  .github/workflows/release.yml
  .github/workflows/review-site.yml
Labels: bug

#579 Closes #578: Update dev dependencies and several linting configuration files.
  .eslintrc.json
  Dockerfile
  build/.eslintrc.json
  build/rollup.config.js
  build/vnu-jar.js
  package-lock.json
  package.json
  site/.eslintrc.json
Labels: dependencies, high priority

#581 Closes #580: Change the Hugo shortcode delimiter in headings that end up in the ToC.
  site/content/docs/2.0/getting-started/contents.md
  site/content/docs/2.0/getting-started/webpack.md
Labels: bug, documentation, high priority
