Repository az-digital/arizona-bootstrap, pull requests merged in 2023-02, with the labels that each got.

#655 Update Github Actions to use major versions
  .github/workflows/cdn-deploy-head.yml
  .github/workflows/cdn-deploy-release.yml
  .github/workflows/release.yml
  .github/workflows/review-site.yml
Labels: enhancement, ci

#653 Closes #652: Add dependabot support for Github actions & Dockerfile
  .github/dependabot.yml
Labels: enhancement, dependencies, ci

#666 Closes #662: Restore breadcrumb padding, remove bottom margin PR #663, rebased onto 2.x.
  .github/dependabot.yml
  .github/workflows/cdn-deploy-head.yml
  .github/workflows/cdn-deploy-release.yml
  .github/workflows/release.yml
  .github/workflows/review-site.yml
  RELEASES.md
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_breadcrumb.scss
Labels: bug

#668 Closes #636, Closes #665: Dependabot configuration changes.
  .github/dependabot.yml
Labels: dependencies, ci
