Repository az-digital/arizona-bootstrap, pull requests merged in 2023-01, with the labels that each got.

#623 Closes #622: Apply routine dev dependency updates.
  .eslintrc.json
  Dockerfile
  build/rollup.config.js
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.js.map
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.js.map
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  package-lock.json
  package.json
  site/assets/js/ie-emulation-modes-warning.js
  site/content/docs/2.0/examples/navbar/index.html
Labels: dependencies, backport

#639 Closes #638: Backports the dev dependency updates from PR #623 to the relevant banch.
  .eslintrc.json
  Dockerfile
  build/rollup.config.js
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.js.map
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.js.map
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  package-lock.json
  package.json
  site/assets/js/ie-emulation-modes-warning.js
  site/content/docs/2.0/examples/navbar/index.html
Labels: dependencies, backport

#645 Closes #644 Allow review sites to be created on PR targeting 2.x branch
  .github/workflows/review-site.yml
Labels: ci

#626 Fixes Issue #625: Remove breadcrumb margins
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/_breadcrumb.scss
Labels: bug, 2.0.x only

#611 Closes #610 Update navbar to account for future versions.
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/favicons.html
Labels: backport

#648 Closes #647 Announce deprecation of main and latest CDN buckets
  README.md
Labels: backport

#650 Set BRANCH_NAME var in dispatch job instead of release job.
  .github/workflows/release.yml
Labels: bug, backport, ci

#651 Update and rename cdn-deploy-main.yml to cdn-deploy-head.yml
  .github/workflows/cdn-deploy-head.yml
  .github/workflows/cdn-deploy-main.yml
Labels: bug, 2.0.x only, ci
