Repository az-digital/arizona-bootstrap, pull requests merged in 2023-06, with the labels that each got.

#793 az-digital/az_quickstart#2331 Change slack channel names from azdigital-general to azdigital-support
  site/data/slack-channels.yml
Labels: documentation, backport

#794 az-digital/az_quickstart#2330 Change slack channel names from friday-meetings to azdigital-meetings
  site/content/docs/2.0/about/get-involved.md
  site/data/slack-channels.yml
Labels: documentation, backport

#796 Closes #795: backport PR #793 and PR #794 to the 2.x branch.
  site/content/docs/2.0/about/get-involved.md
  site/data/slack-channels.yml
Labels: documentation, 2.0.x only

#791 Closes #789: Apply June dev dependency updates.
  Dockerfile
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  hugo_template.yml
  package-lock.json
  package.json
Labels: dependencies

#792 Closes #790: backport dev dependency updates to the 2.x branch.
  Dockerfile
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  hugo_template.yml
  package-lock.json
  package.json
Labels: dependencies, 2.0.x only
