Repository az-digital/arizona-bootstrap, pull requests merged in 2023-08, with the labels that each got.

#852 Closes #849: backport late July dev dependency version bumps.
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, 2.0.x only

#851 Closes #848: apply late July dev dependency version bumps.
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, backport

#873 Closes #878 Update Github actions secret name for dependabot (2.x)
  .github/workflows/review-site.yml
Labels: backport, 2.0.x only, ci

#899 Closes #887: Address off-canvas menu usability issues on iOS
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_navbar-offcanvas.scss
  site/content/docs/2.0/components/navbar-off-canvas.md
Labels: bug, 2.0.x only

#900 az-digital/az_quickstart#2549 fix mobile horizontal scroll.
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_custom-styles.scss
Labels: bug

#901 az-digital/az_quickstart#2549 fix mobile horizontal scroll.
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_custom-styles.scss
Labels: bug, 2.0.x only
