Repository az-digital/arizona-bootstrap, pull requests merged in 2024-05, with the labels that each got.

#1217 #1215 Update Arizona Digital email address in Arizona Bootstrap 2.x Docs.
  CONTRIBUTING.md
  site/content/docs/2.0/about/get-involved.md
Labels: documentation, low priority

#1216 #1215 Update Arizona Digital email address in Arizona Bootstrap 5.x Docs.
  CONTRIBUTING.md
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.esm.min.js
  dist/js/arizona-bootstrap.esm.min.js.map
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  package-lock.json
  site/content/docs/5.0/about/get-involved.md
Labels: documentation

#1229 Closes #1227; manually bump the version numbers within the Dockerfile.
  Dockerfile
  package-lock.json
Labels: dependencies

#1230 Closes #1228: Backport the Dockerfile changes from the main branch.
  Dockerfile
  package-lock.json
Labels: dependencies, 2.0.x only
