Repository az-digital/arizona-bootstrap, pull requests merged in 2024-01, with the labels that each got.

#1107 Closes Issue #1105: backport dev dependency updates to the 2.x branch.
  Dockerfile
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.js.map
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.min.js
  package-lock.json
  package.json
Labels: dependencies, 2.0.x only

#1106 Closes Issue #1104: catch up with upstream Bootstrap dev dependency updates.
  Dockerfile
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.esm.js
  dist/js/arizona-bootstrap.esm.min.js
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.min.js
  package-lock.json
  package.json
Labels: dependencies

#1036 Closes #1016: Convert build scripts to ESM.
  .eslintrc.json
  build/banner.mjs
  build/build-plugins.mjs
  build/postcss.config.js
  build/postcss.config.mjs
  build/rollup.config.mjs
  build/vnu-jar.mjs
  package-lock.json
  package.json
Labels: dependencies, ci

#1124 Closes #1122: Add callout variants for all theme colors. (2.x)
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/_callout.scss
  site/content/docs/2.0/components/callouts.md
Labels: enhancement, 2.0.x only
