Repository az-digital/arizona-bootstrap, pull requests merged in 2025-05, with the labels that each got.

#1428 Closes #1416: Change accordion background for Arizona Bootstrap 5 and remove rounded corners globally
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/arizona-bootstrap.scss
  scss/override/_accordion.scss
  scss/override/_variables.scss
  site/content/docs/5.0/components/collapse.md
  site/data/nav.yml
Labels: enhancement, visual change

#1443 Closes #1401, #1417, and #1419: Add text, border, and background colors with opacity using Utilities API. Add brand colors as RGB CSS custom properties
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  dist/js/arizona-bootstrap.bundle.js
  dist/js/arizona-bootstrap.bundle.js.map
  dist/js/arizona-bootstrap.bundle.min.js
  dist/js/arizona-bootstrap.bundle.min.js.map
  dist/js/arizona-bootstrap.esm.js
  dist/js/arizona-bootstrap.esm.js.map
  dist/js/arizona-bootstrap.esm.min.js
  dist/js/arizona-bootstrap.esm.min.js.map
  dist/js/arizona-bootstrap.js
  dist/js/arizona-bootstrap.js.map
  dist/js/arizona-bootstrap.min.js
  dist/js/arizona-bootstrap.min.js.map
  package-lock.json
  scss/arizona-bootstrap.scss
  scss/custom/_styles.scss
  scss/legacy/_card.scss
  scss/override/_maps.scss
  scss/override/_utilities.scss
  site/assets/scss/docs.scss
  site/content/docs/5.0/helpers/color-background.md
  site/content/docs/5.0/utilities/background.md
  site/content/docs/5.0/utilities/borders.md
  site/content/docs/5.0/utilities/colors.md
  site/data/colors.yml
  site/data/grays.yml
Labels: enhancement, 5.x

#1451 Closes #1402, #1418: Update font and typography for Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/arizona-bootstrap.scss
  scss/custom/_styles.scss
  scss/custom/_typography.scss
  scss/custom/_variables.scss
  scss/override/_reboot.scss
  scss/override/_typography.scss
  scss/override/_variables.scss
  site/assets/scss/_custom-docs.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/content/font.md
  site/content/docs/5.0/content/typography.md
  site/content/docs/5.0/utilities/text.md
  site/data/sidebar.yml
Labels: 5.x

#1457 Closes #1456: Move deprecated accordion/collapse styles to new deprecated folder
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css.map
  scss/arizona-bootstrap.scss
  scss/deprecated/_accordion.scss
  scss/legacy/_deprecated.scss
  scss/override/_accordion.scss
Labels: 5.x

#1431 Closes 1421: Change button style for Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  package-lock.json
  scss/arizona-bootstrap.scss
  scss/custom/_button-group.scss
  scss/custom/_buttons.scss
  scss/legacy/_button.scss
  scss/legacy/_mixins.scss
  scss/mixins/_buttons.scss
  scss/override/_buttons.scss
  scss/override/_variables.scss
  site/content/docs/5.0/components/button-group.md
  site/content/docs/5.0/components/buttons.md
  site/content/docs/5.0/components/input-group.md
  site/content/docs/5.0/forms/input-group.md
Labels: visual change, 5.x

#1481 Use BS5 border radius mixins for custom nav styling
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/override/_nav.scss
Labels: 5.x

#1471 Closes #1403: Update styling of navs and tabs for Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/custom/_variables.scss
  scss/legacy/_variables.scss
  scss/override/_nav.scss
  scss/override/_variables.scss
  site/assets/scss/_custom-docs.scss
  site/content/docs/5.0/components/navs-tabs.md
  site/content/docs/5.0/components/navs.md
  site/data/nav.yml
Labels: 5.x

#1482 Closes #1438: Add Icon for Arizona Bootstrap
  package-lock.json
  site/content/docs/5.0/components/navbar.md
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/footer.html
  site/layouts/partials/home/get-started.html
  site/layouts/partials/home/masthead.html
  site/layouts/partials/icons/arizona-bootstrap-black-background-thick.svg
  site/layouts/partials/icons/arizona-bootstrap-black-thick.svg
  site/layouts/partials/icons/arizona-bootstrap-white-background-thick.svg
  site/layouts/partials/icons/arizona-bootstrap-white-thick.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--black-background.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--black-transparent.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--black-transparent@2x.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--white-background.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--white-transparent.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-black-background-thick.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-black-thick.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-white-background-thick.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-white-thick.svg
Labels: 5.x

#1478 Closes #1477: Add old accordion implementation details to backwards compatibility page in V5
  site/content/docs/5.0/backwards-compatibility.md
Labels: 5.x

#1476 Closes #1473: Vertical button groups in Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/arizona-bootstrap.scss
  scss/override/_button-group.scss
Labels: visual change, 5.x

#1460 Closes #1404: Update Arizona Header for Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/custom/_styles.scss
  site/content/docs/5.0/components/arizona-header.md
  site/data/nav.yml
  site/data/sidebar.yml
Labels: 5.x

#1488 Closes #1485: Add colorized versions of the AZ Bootstrap logo, favicon, and modify alt texts to "Arizona Bootstrap"
  site/assets/scss/_navbar.scss
  site/content/docs/5.0/components/navbar.md
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/footer.html
  site/layouts/partials/home/masthead.html
  site/layouts/partials/icons/arizona-bootstrap-black-background-solid-cactus.svg
  site/layouts/partials/icons/arizona-bootstrap-black-background.svg
  site/layouts/partials/icons/arizona-bootstrap-black.svg
  site/layouts/partials/icons/arizona-bootstrap-color.svg
  site/layouts/partials/icons/arizona-bootstrap-colored-background.svg
  site/layouts/partials/icons/arizona-bootstrap-white-background.svg
  site/layouts/partials/icons/arizona-bootstrap-white.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--colored-background.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo--colored-background@2x.png
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-black-background-solid-cactus.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-black-background.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-black.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-color.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-colored-background-solid-cactus.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-colored-background.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-white-background-solid-cactus.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-white-background.svg
  site/static/docs/5.0/assets/brand/arizona-bootstrap-logo-white.svg
  site/static/docs/5.0/assets/img/favicons/favicon-16x16.png
  site/static/docs/5.0/assets/img/favicons/favicon-32x32.png
  site/static/docs/5.0/assets/img/favicons/favicon.ico
Labels: documentation, enhancement, 5.x

#1487 Closes #1480: Add style for Custom Arizona Bootstrap badges to the docs
  site/assets/scss/_custom-docs.scss
  site/content/docs/5.0/components/arizona-header.md
  site/content/docs/5.0/components/button-group.md
  site/content/docs/5.0/components/buttons.md
  site/content/docs/5.0/components/navs-tabs.md
Labels: documentation, enhancement, 5.x

#1454 Closes #1420: Add icons for Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  hugo_template.yml
  scss/arizona-bootstrap.scss
  scss/custom/_navbar-offcanvas.scss
  scss/deprecated/_accordion.scss
  scss/legacy/_custom-asset-overrides.scss
  scss/override/_breadcrumb.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/breadcrumb.md
  site/content/docs/5.0/components/navbar-off-canvas.md
  site/content/docs/5.0/examples/navbar/index.html
  site/content/docs/5.0/icons.md
  site/layouts/partials/alert-warning-material-design.md
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/home/masthead-followup.html
  site/layouts/partials/stylesheet.html
Labels: visual change, 5.x

#1522 Closes #1497: Add /dist to gitignore, don't update /dist assets in PR branches automatically. (2.x)
  .github/workflows/review-site.yml
  .gitignore
Labels: backport, 2.0.x only, ci

#1498 Closes #1492: Deprecate the .nav-tabs-lg custom class in Arizona Bootstrap 5
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css.map
  scss/arizona-bootstrap.scss
  scss/deprecated/_nav.scss
  scss/override/_nav.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/navs-tabs.md
Labels: 5.x

#1525 Closes #1524: Use different GH token for pushing dist assets in review site workflow.
  .github/workflows/review-site.yml
Labels: bug, ci, 5.x

#1518 Closes #1516: Replace Contextual colors with Brand colors in doc pages where Brand colors make more sense
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.min.css
  scss/override/_utilities.scss
  site/content/docs/5.0/components/badge.md
  site/content/docs/5.0/components/buttons.md
  site/content/docs/5.0/components/card.md
  site/content/docs/5.0/components/dropdowns.md
  site/content/docs/5.0/components/placeholders.md
  site/content/docs/5.0/components/spinners.md
  site/content/docs/5.0/helpers/color-background.md
  site/content/docs/5.0/helpers/focus-ring.md
  site/content/docs/5.0/utilities/background.md
  site/content/docs/5.0/utilities/borders.md
  site/content/docs/5.0/utilities/colors.md
  site/data/pnc-colors.yml
Labels: documentation, 5.x

#1509 Closes #1508: Remove hard-coded 2.x reference in release workflow in preparation for creating 5.x releases.
  .github/workflows/release.yml
Labels: ci, 5.x

#1519 Closes #1517: Adjust callouts to be WCAG compliant
  .github/workflows/release.yml
  dist/css/arizona-bootstrap.css
  dist/css/arizona-bootstrap.css.map
  dist/css/arizona-bootstrap.min.css
  dist/css/arizona-bootstrap.min.css.map
  scss/legacy/_callout.scss
  site/content/docs/5.0/components/callouts.md
  site/data/sidebar.yml
Labels: 5.x

#1527 Remove the --force on the GitHub Actions push of changes back to the repository.
  .github/workflows/review-site.yml
Labels: ci

#1505 Closes #1504 Update spacing utilities styling and docs for Arizona Bootstrap 5
  scss/override/_variables.scss
  site/assets/scss/_custom-docs.scss
  site/content/docs/5.0/utilities/spacing.md
Labels: 5.x

#1529 Closes #1528: Only update CDN assets if /dist was updated.
  .github/workflows/cdn-deploy-head.yml
Labels: bug, enhancement, ci

#1531 #1526: Remove the --force on the GitHub Actions push of changes back to the repository. (2.x)
  .github/workflows/review-site.yml
Labels: bug, backport, 2.0.x only, ci

#1515 Closes #1514: Update sidebar menu with 2.0 items and remove obsolete docs files
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/background-wrappers.md
  site/content/docs/5.0/components/callouts.md
  site/content/docs/5.0/components/forms.md
  site/content/docs/5.0/components/horizontal-rule.md
  site/content/docs/5.0/components/jumbotron.md
  site/content/docs/5.0/components/media-object.md
  site/content/docs/5.0/components/photo-gallery.md
  site/content/docs/5.0/utilities/clearfix.md
  site/content/docs/5.0/utilities/close-icon.md
  site/content/docs/5.0/utilities/column-split.md
  site/content/docs/5.0/utilities/embed.md
  site/content/docs/5.0/utilities/image-replacement.md
  site/content/docs/5.0/utilities/screen-readers.md
  site/data/nav.yml
  site/data/sidebar.yml
Labels: 5.x

#1530 Closes #1510: Restore and update the Hover docs page for Arizona Bootstrap 5
  site/content/docs/5.0/utilities/hover.md
  site/data/sidebar.yml
Labels: 5.x

#1534 Closes #1533: Move our deprecated scss to the top of the list of Arizona Bootstrap imports
  scss/arizona-bootstrap.scss
Labels: 5.x

#1535 Closes #1405: Update input groups for Arizona Bootstrap 5
  scss/override/_forms.scss
  site/content/docs/5.0/forms/input-group.md
Labels: 5.x

#1543 Closes #1541, Closes #1542: Update the GitHub Actions and Dependabot config to cover changes since the last release.
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/release.yml
Labels: ci

#1470 Closes #1415: Remove primary and secondary theme colors, update custom callouts component
  scss/arizona-bootstrap.scss
  scss/custom/_callouts.scss
  scss/custom/_variables.scss
  scss/legacy/_callout.scss
  scss/legacy/_mixins.scss
  scss/mixins/_callouts.scss
  scss/override/_maps.scss
  scss/override/_variables.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/callouts.md
Labels: 5.x
