Repository az-digital/arizona-bootstrap, pull requests merged in 2025-07, with the labels that each got.

#1590 Closes #1589: Remove certain brand colors as gradient and transparent backgrounds
  scss/custom/_background.scss
  scss/custom/_color-background.scss
  site/content/docs/5.0/components/callouts.md
  site/content/docs/5.0/components/card.md
  site/content/docs/5.0/helpers/color-background.md
  site/content/docs/5.0/utilities/background.md
  site/content/docs/5.0/utilities/hover.md
Labels: 5.x

#1605 Closes #1597: Update dropdown styling for Arizona Bootstrap 5
  scss/arizona-bootstrap.scss
  scss/custom/_navbar-offcanvas.scss
  scss/legacy/_variables.scss
  scss/override/_dropdown.scss
  scss/override/_variables.scss
Labels: 5.x

#1615 Closes 1614: Improve upgrade documentation for accordion component
  site/content/docs/5.0/backwards-compatibility.md
Labels: documentation

#1629 Closes #1624: make ignore conditions for Dependabot visible and pin dependency versions.
  .eslintrc.json
  .github/dependabot.yml
  package.json
Labels: dependencies, ci

#1612 Closes #1466, #1503, #1609: Update table styling and docs for Arizona Bootstrap 5
  scss/arizona-bootstrap.scss
  scss/legacy/_table.scss
  scss/legacy/_variables.scss
  scss/override/_variables.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/content/tables.md
Labels: 5.x

#1634 Closes #1577: Update Node.js from 20 to 22 in the environment used for CI/CD and local development.
  Dockerfile
Labels: ci

#1621 Closes #1616: Updates Material Symbols reference and removes Icons page
  scss/custom/_navbar-offcanvas.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/arizona-header.md
  site/content/docs/5.0/components/navbar-off-canvas.md
  site/content/docs/5.0/components/photo-gallery.md
  site/content/docs/5.0/examples/navbar/index.html
  site/content/docs/5.0/extend/icons.md
  site/content/docs/5.0/icons.md
  site/data/sidebar.yml
  site/layouts/partials/alert-warning-material-design.md
  site/layouts/partials/home/masthead-followup.html
  site/layouts/partials/stylesheet.html
Labels: documentation, dependencies, 5.x

#1639 Closes #1638: Fixes multiple problems in the documentation .js files.
  site/assets/js/custom-docs.js
  site/content/docs/5.0/content/font.md
  site/content/docs/5.0/forms/validation.md
  site/static/docs/5.0/assets/js/font-sample.js
Labels: documentation, javascript, 5.x

#1647 Closes #1646: Portrait images are not cropped correctly in Photo Galleries with Slider Crop style
  scss/custom/_photo-gallery.scss
  site/content/docs/5.0/components/photo-gallery.md
Labels: 5.x

#1641 Closes #1640: Remove any references to StackBlitz from the docs.
  site/assets/js/snippets.js
  site/layouts/partials/scripts.html
  site/layouts/shortcodes/example.html
Labels: documentation, low priority, 5.x
