Repository az-digital/arizona-bootstrap, pull requests merged in 2025-09, with the labels that each got.

#1709 Closes #1672, closes #1655: Refactor subresource integrity (SRI) hash generation.
  .github/workflows/release.yml
  package.json
  scripts/create-release.sh
Labels: high priority, ci, 5.x

#1713 Closes #1712: Right-justify content in the Arizona Header except for the wordmark logo
  scss/custom/_arizona-header.scss
Labels: 5.x

#1719 Closes #1718: Remove bold from links
  scss/arizona-bootstrap.scss
  scss/override/_reboot.scss
Labels: 5.x

#1716 Closes #1715: Navbar dropdowns do not wrap text
  scss/override/_navbar.scss
  site/assets/scss/_custom-docs.scss
  site/content/docs/5.0/components/navbar.md
Labels: 5.x

#1743 Closes #1742: Update Arizona Header buttons to have sharp corners
  scss/custom/_arizona-header.scss
Labels: 5.x

#1728 Closes #1720: Add custom focus-visible styles
  scss/arizona-bootstrap.scss
  scss/custom/_arizona-header.scss
  scss/custom/_photo-gallery.scss
  scss/mixins/_az-color-contrast.scss
  scss/override/_carousel.scss
  scss/override/_dropdown.scss
  scss/override/_nav.scss
  scss/override/_typography.scss
  scss/override/_variables.scss
  site/content/docs/5.0/components/buttons.md
Labels: high priority, accessibility, 5.x
