Repository az-digital/arizona-bootstrap, pull requests merged in 2025-08, with the labels that each got.

#1660 Closes #1651: Update "Custom Arizona Bootstrap Class" styling on Typography page
  site/content/docs/5.0/content/typography.md
Labels: 5.x

#1667 #1665: Add ignore line for hash placeholder values back to vnu_jar.mjs script.
  build/vnu-jar.mjs
Labels: bug

#1664 Closes #1662: Delete the obsolete Deprecated page
  site/content/docs/5.0/deprecated.md
Labels: 5.x

#1679 Closes #1673: Adds note about bg-transparent class to Color & Background page
  site/content/docs/5.0/helpers/color-background.md
Labels: documentation, 5.x

#1690 Closes #1689: Update pagination focus and active colors to blue
  scss/override/_variables.scss
Labels: 5.x

#1693 Closes #1692: Disable dark mode
  hugo_template.yml
  scss/custom/_photo-gallery.scss
  scss/override/_variables.scss
  site/content/docs/5.0/components/carousel.md
  site/content/docs/5.0/components/close-button.md
  site/content/docs/5.0/components/dropdowns.md
  site/content/docs/5.0/components/navbar.md
  site/content/docs/5.0/components/offcanvas.md
  site/layouts/_default/baseof.html
  site/layouts/_default/examples.html
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/header.html
Labels: 5.x
