Repository az-digital/arizona-bootstrap, pull requests merged in 2025-06, with the labels that each got.

#1555 Closes #1552: Add callout-info back to callouts page
  scss/custom/_callouts.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/callouts.md
Labels: 5.x

#1566 Closes #921, Closes #993: Various improvements to GH actions release workflow.
  .github/workflows/release.yml
Labels: enhancement, ci

#1549 Closes #1538: Update photo gallery markup with Bootstrap 5 classes and data attribute names.
  scss/custom/_photo-gallery.scss
  site/content/docs/5.0/components/photo-gallery.md
Labels: 5.x

#1575 Closes #1574: Remove unused alerts customization in Arizona Bootstrap 5
  scss/legacy/_mixins.scss
Labels: 5.x

#1568 Closes #1567: Prevent photo gallery captions from overlapping images on mobile devices
  scss/custom/_photo-gallery.scss
  site/content/docs/5.0/components/photo-gallery.md
  site/static/docs/5.0/assets/img/photo-gallery-demo/gallery-img-1-thumb.jpg
  site/static/docs/5.0/assets/img/photo-gallery-demo/gallery-img-1.jpg
  site/static/docs/5.0/assets/img/photo-gallery-demo/gallery-img-2-thumb.jpg
  site/static/docs/5.0/assets/img/photo-gallery-demo/gallery-img-2.jpg
Labels: enhancement, 5.x

#1559 Closes #1551: Update card component for Arizona Bootstrap 5
  scss/arizona-bootstrap.scss
  scss/custom/_card.scss
  scss/deprecated/_card.scss
  scss/legacy/_card.scss
  scss/legacy/_variables.scss
  scss/override/_typography.scss
  scss/override/_variables.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/card.md
Labels: 5.x

#1585 Closes #1584: Update Badge component for Arizona Bootstrap 5
  scss/arizona-bootstrap.scss
  scss/custom/_badge.scss
  scss/legacy/_badge.scss
  scss/legacy/_mixins.scss
  scss/legacy/_variables.scss
  scss/override/_badge.scss
  site/content/docs/5.0/backwards-compatibility.md
  site/content/docs/5.0/components/badge.md
Labels: 5.x
